### ISSUE TITLE
Please provide requirements file

### ISSUE THREAD

**Issue by abishpius** [Xiaojiu-z/Stable-Hair#11]
Getting following error, I have set up diffusers installation.

Traceback (most recent call last):
  File "/content/Stable-Hair/gradio_demo_full.py", line 9, in <module>
    from diffusers import DDIMScheduler, UniPCMultistepScheduler
  File "/content/Stable-Hair/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/content/Stable-Hair/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/content/Stable-Hair/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

**Comment by Xiaojiu-z** [comment]
got it~
